name: Deploy artoflynn.codewithsky.co.ke

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      # 2. Load SSH key
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3. Add server fingerprint
      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      # # 4. Test SSH connection
      # - name: SSH Test
      #   run: |
      #     ssh -T -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} exit

      # 5. Deployment commands
      - name: Deploy codewithsky
        run: |
          ssh -T -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            # Create target folder if missing
            mkdir -p ~/artoflynn.codewithsky.co.ke
            cd ~/artoflynn.codewithsky.co.ke

            # Git setup
            if [ ! -d ".git" ]; then
                GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_artoflynn" git init
                git remote add origin git@github.com:Bkimking/artorlynn.git
                GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_artoflynn" git fetch origin
                git checkout -f main
            else
                GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519_artoflynn" git fetch origin
                git reset --hard origin/main
            fi

            # Install dependencies
            composer install --no-dev --optimize-autoloader

            # Laravel deployment
            php artisan migrate --force
            php artisan optimize:clear
            php artisan optimize

            echo "Deployment complete"
          EOF
          